using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Security;
using System.Text;

namespace OnlineLeaveManagementSystem.Infrastructure
{
    public static class ReportExportBuilder
    {
        public static byte[] BuildCsv(DataTable table)
        {
            StringBuilder builder = new StringBuilder();
            builder.AppendLine("Employee,Username,Department,Leave Type,Start Date,End Date,Days,Status,Attachment Link,Submitted At,Reviewed By,Reviewed At,Review Comment,Reason");

            foreach (DataRow row in table.Rows)
            {
                builder
                    .Append(CsvValue(Convert.ToString(row["FullName"]))).Append(',')
                    .Append(CsvValue(Convert.ToString(row["Username"]))).Append(',')
                    .Append(CsvValue(Convert.ToString(row["Department"]))).Append(',')
                    .Append(CsvValue(Convert.ToString(row["LeaveType"]))).Append(',')
                    .Append(CsvValue(FormatDate(row["StartDate"]))).Append(',')
                    .Append(CsvValue(FormatDate(row["EndDate"]))).Append(',')
                    .Append(CsvValue(Convert.ToString(row["RequestedDays"]))).Append(',')
                    .Append(CsvValue(Convert.ToString(row["Status"]))).Append(',')
                    .Append(CsvValue(GetAttachmentExportValue(row))).Append(',')
                    .Append(CsvValue(FormatDateTime(row["CreatedAt"]))).Append(',')
                    .Append(CsvValue(Convert.ToString(row["ReviewedByName"]))).Append(',')
                    .Append(CsvValue(FormatDateTime(row["ReviewedAt"]))).Append(',')
                    .Append(CsvValue(Convert.ToString(row["ReviewComment"]))).Append(',')
                    .Append(CsvValue(Convert.ToString(row["Reason"])))
                    .AppendLine();
            }

            return Encoding.UTF8.GetPreamble().Concat(Encoding.UTF8.GetBytes(builder.ToString())).ToArray();
        }

        public static byte[] BuildPdf(DataTable table, string title, IEnumerable<string> filterSummary, string generatedBy)
        {
            List<string> lines = new List<string>
            {
                title,
                string.Format("Generated by: {0}", generatedBy),
                string.Format("Generated at: {0:dd MMM yyyy HH:mm}", DateTime.Now)
            };

            foreach (string filter in filterSummary)
            {
                if (!string.IsNullOrWhiteSpace(filter))
                {
                    lines.Add(filter);
                }
            }

            lines.Add(string.Format("Records: {0} | Days: {1:0.#}", table.Rows.Count, GetTotalDays(table)));
            lines.Add(string.Empty);

            foreach (DataRow row in table.Rows)
            {
                lines.Add(string.Format(
                    "{0} | {1} | {2} | {3} | {4} day(s) | {5}",
                    Convert.ToString(row["FullName"]),
                    Convert.ToString(row["Department"]),
                    Convert.ToString(row["LeaveType"]),
                    string.Format("{0} to {1}", FormatDate(row["StartDate"]), FormatDate(row["EndDate"])),
                    Convert.ToString(row["RequestedDays"]),
                    Convert.ToString(row["Status"])));

                string reason = Convert.ToString(row["Reason"]);
                if (!string.IsNullOrWhiteSpace(reason))
                {
                    lines.Add("Reason: " + reason);
                }

                string reviewComment = Convert.ToString(row["ReviewComment"]);
                if (!string.IsNullOrWhiteSpace(reviewComment))
                {
                    lines.Add("Review: " + reviewComment);
                }

                string attachmentUrl = GetAttachmentExportValue(row);
                if (!string.IsNullOrWhiteSpace(attachmentUrl))
                {
                    lines.Add("Attachment: " + attachmentUrl);
                }

                lines.Add(string.Empty);
            }

            return BuildSimplePdf(lines);
        }

        public static byte[] BuildDocx(DataTable table, string title, IEnumerable<string> filterSummary, string generatedBy)
        {
            using (MemoryStream stream = new MemoryStream())
            {
                using (ZipArchive archive = new ZipArchive(stream, ZipArchiveMode.Create, true))
                {
                    WriteArchiveEntry(archive, "[Content_Types].xml", GetContentTypesXml());
                    WriteArchiveEntry(archive, "_rels/.rels", GetRootRelationshipsXml());
                    WriteArchiveEntry(archive, "word/_rels/document.xml.rels", GetDocumentRelationshipsXml());
                    WriteArchiveEntry(archive, "word/document.xml", GetDocumentXml(table, title, filterSummary, generatedBy));
                }

                return stream.ToArray();
            }
        }

        private static string GetDocumentXml(DataTable table, string title, IEnumerable<string> filterSummary, string generatedBy)
        {
            StringBuilder builder = new StringBuilder();
            builder.Append("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>");
            builder.Append("<w:document xmlns:w=\"http://schemas.openxmlformats.org/wordprocessingml/2006/main\">");
            builder.Append("<w:body>");
            AppendParagraph(builder, title, true);
            AppendParagraph(builder, string.Format("Generated by: {0}", generatedBy), false);
            AppendParagraph(builder, string.Format("Generated at: {0:dd MMM yyyy HH:mm}", DateTime.Now), false);

            foreach (string filter in filterSummary)
            {
                if (!string.IsNullOrWhiteSpace(filter))
                {
                    AppendParagraph(builder, filter, false);
                }
            }

            AppendParagraph(builder, string.Format("Records: {0} | Days: {1:0.#}", table.Rows.Count, GetTotalDays(table)), false);
            builder.Append("<w:tbl>");
            builder.Append("<w:tblPr><w:tblW w:w=\"0\" w:type=\"auto\"/></w:tblPr>");
            builder.Append("<w:tr>");
            AppendTableCell(builder, "Employee", true);
            AppendTableCell(builder, "Department", true);
            AppendTableCell(builder, "Leave Type", true);
            AppendTableCell(builder, "Date Range", true);
            AppendTableCell(builder, "Days", true);
            AppendTableCell(builder, "Status", true);
            AppendTableCell(builder, "Attachment Link", true);
            AppendTableCell(builder, "Reason", true);
            builder.Append("</w:tr>");

            foreach (DataRow row in table.Rows)
            {
                builder.Append("<w:tr>");
                AppendTableCell(builder, Convert.ToString(row["FullName"]), false);
                AppendTableCell(builder, Convert.ToString(row["Department"]), false);
                AppendTableCell(builder, Convert.ToString(row["LeaveType"]), false);
                AppendTableCell(builder, string.Format("{0} to {1}", FormatDate(row["StartDate"]), FormatDate(row["EndDate"])), false);
                AppendTableCell(builder, Convert.ToString(row["RequestedDays"]), false);
                AppendTableCell(builder, Convert.ToString(row["Status"]), false);
                AppendTableCell(builder, GetAttachmentExportValue(row), false);
                AppendTableCell(builder, Convert.ToString(row["Reason"]), false);
                builder.Append("</w:tr>");
            }

            builder.Append("</w:tbl>");
            builder.Append("<w:sectPr><w:pgSz w:w=\"12240\" w:h=\"15840\"/><w:pgMar w:top=\"1440\" w:right=\"1440\" w:bottom=\"1440\" w:left=\"1440\"/></w:sectPr>");
            builder.Append("</w:body></w:document>");
            return builder.ToString();
        }

        private static byte[] BuildSimplePdf(IList<string> lines)
        {
            const int linesPerPage = 44;
            List<string> pages = new List<string>();

            for (int index = 0; index < lines.Count; index += linesPerPage)
            {
                IEnumerable<string> pageLines = lines.Skip(index).Take(linesPerPage);
                StringBuilder content = new StringBuilder();
                content.AppendLine("BT");
                content.AppendLine("/F1 10 Tf");
                content.AppendLine("40 780 Td");
                content.AppendLine("14 TL");

                bool isFirst = true;
                foreach (string line in pageLines)
                {
                    string escaped = EscapePdfText(line);
                    if (isFirst)
                    {
                        content.AppendFormat("({0}) Tj", escaped).AppendLine();
                        isFirst = false;
                    }
                    else
                    {
                        content.AppendFormat("T* ({0}) Tj", escaped).AppendLine();
                    }
                }

                content.AppendLine("ET");
                pages.Add(content.ToString());
            }

            if (pages.Count == 0)
            {
                pages.Add("BT /F1 10 Tf 40 780 Td (No records found.) Tj ET");
            }

            List<byte[]> objects = new List<byte[]>();
            objects.Add(Encoding.ASCII.GetBytes("<< /Type /Catalog /Pages 2 0 R >>"));

            string[] pageObjectRefs = new string[pages.Count];
            for (int index = 0; index < pages.Count; index++)
            {
                pageObjectRefs[index] = (3 + (index * 2)) + " 0 R";
            }

            objects.Add(Encoding.ASCII.GetBytes(string.Format("<< /Type /Pages /Kids [{0}] /Count {1} >>", string.Join(" ", pageObjectRefs), pages.Count)));

            int fontObjectId = 3 + (pages.Count * 2);
            for (int index = 0; index < pages.Count; index++)
            {
                int contentObjectId = 4 + (index * 2);
                byte[] contentBytes = Encoding.ASCII.GetBytes(pages[index]);
                objects.Add(Encoding.ASCII.GetBytes(string.Format("<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 {0} 0 R >> >> /Contents {1} 0 R >>", fontObjectId, contentObjectId)));
                objects.Add(Encoding.ASCII.GetBytes(string.Format("<< /Length {0} >>\nstream\n{1}\nendstream", contentBytes.Length, pages[index])));
            }

            objects.Add(Encoding.ASCII.GetBytes("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>"));

            using (MemoryStream stream = new MemoryStream())
            using (BinaryWriter writer = new BinaryWriter(stream, Encoding.ASCII))
            {
                writer.Write(Encoding.ASCII.GetBytes("%PDF-1.4\n"));
                List<long> offsets = new List<long> { 0 };

                for (int index = 0; index < objects.Count; index++)
                {
                    offsets.Add(stream.Position);
                    writer.Write(Encoding.ASCII.GetBytes(string.Format("{0} 0 obj\n", index + 1)));
                    writer.Write(objects[index]);
                    writer.Write(Encoding.ASCII.GetBytes("\nendobj\n"));
                }

                long xrefPosition = stream.Position;
                writer.Write(Encoding.ASCII.GetBytes(string.Format("xref\n0 {0}\n", objects.Count + 1)));
                writer.Write(Encoding.ASCII.GetBytes("0000000000 65535 f \n"));
                for (int index = 1; index < offsets.Count; index++)
                {
                    writer.Write(Encoding.ASCII.GetBytes(string.Format("{0:0000000000} 00000 n \n", offsets[index])));
                }

                writer.Write(Encoding.ASCII.GetBytes(string.Format("trailer\n<< /Size {0} /Root 1 0 R >>\nstartxref\n{1}\n%%EOF", objects.Count + 1, xrefPosition)));
                writer.Flush();
                return stream.ToArray();
            }
        }

        private static void AppendParagraph(StringBuilder builder, string text, bool bold)
        {
            builder.Append("<w:p><w:r>");
            if (bold)
            {
                builder.Append("<w:rPr><w:b/></w:rPr>");
            }

            builder.Append("<w:t xml:space=\"preserve\">").Append(XmlEscape(text)).Append("</w:t>");
            builder.Append("</w:r></w:p>");
        }

        private static void AppendTableCell(StringBuilder builder, string text, bool bold)
        {
            builder.Append("<w:tc><w:p><w:r>");
            if (bold)
            {
                builder.Append("<w:rPr><w:b/></w:rPr>");
            }

            builder.Append("<w:t xml:space=\"preserve\">").Append(XmlEscape(text)).Append("</w:t>");
            builder.Append("</w:r></w:p></w:tc>");
        }

        private static string GetContentTypesXml()
        {
            return "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>" +
                   "<Types xmlns=\"http://schemas.openxmlformats.org/package/2006/content-types\">" +
                   "<Default Extension=\"rels\" ContentType=\"application/vnd.openxmlformats-package.relationships+xml\"/>" +
                   "<Default Extension=\"xml\" ContentType=\"application/xml\"/>" +
                   "<Override PartName=\"/word/document.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml\"/>" +
                   "</Types>";
        }

        private static string GetRootRelationshipsXml()
        {
            return "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>" +
                   "<Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\">" +
                   "<Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument\" Target=\"word/document.xml\"/>" +
                   "</Relationships>";
        }

        private static string GetDocumentRelationshipsXml()
        {
            return "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>" +
                   "<Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"></Relationships>";
        }

        private static void WriteArchiveEntry(ZipArchive archive, string entryPath, string content)
        {
            ZipArchiveEntry entry = archive.CreateEntry(entryPath, CompressionLevel.Optimal);
            using (StreamWriter writer = new StreamWriter(entry.Open(), new UTF8Encoding(false)))
            {
                writer.Write(content);
            }
        }

        private static string CsvValue(string value)
        {
            string normalized = value ?? string.Empty;
            return "\"" + normalized.Replace("\"", "\"\"") + "\"";
        }

        private static string GetAttachmentExportValue(DataRow row)
        {
            if (row == null)
            {
                return string.Empty;
            }

            if (row.Table.Columns.Contains("AttachmentExportUrl"))
            {
                return Convert.ToString(row["AttachmentExportUrl"]);
            }

            if (row.Table.Columns.Contains("AttachmentPath"))
            {
                return Convert.ToString(row["AttachmentPath"]);
            }

            return string.Empty;
        }

        private static string FormatDate(object value)
        {
            return value == null || value == DBNull.Value ? string.Empty : Convert.ToDateTime(value).ToString("dd MMM yyyy");
        }

        private static string FormatDateTime(object value)
        {
            return value == null || value == DBNull.Value ? string.Empty : Convert.ToDateTime(value).ToString("dd MMM yyyy HH:mm");
        }

        private static decimal GetTotalDays(DataTable table)
        {
            decimal total = 0;
            foreach (DataRow row in table.Rows)
            {
                total += row["RequestedDays"] == DBNull.Value ? 0 : Convert.ToDecimal(row["RequestedDays"]);
            }

            return total;
        }

        private static string EscapePdfText(string value)
        {
            return (value ?? string.Empty)
                .Replace("\\", "\\\\")
                .Replace("(", "\\(")
                .Replace(")", "\\)");
        }

        private static string XmlEscape(string value)
        {
            return SecurityElement.Escape(value ?? string.Empty) ?? string.Empty;
        }
    }
}
