//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineLeaveManagementSystem
{
    public partial class ApplyLeave
    {
        protected global::System.Web.UI.WebControls.Label lblSuccessMessage;

        protected global::System.Web.UI.WebControls.Label lblPolicyTitle;

        protected global::System.Web.UI.WebControls.Label lblPolicyText;

        protected global::System.Web.UI.WebControls.Label lblHolidayCalculationHint;

        protected global::System.Web.UI.WebControls.Repeater rptBalances;

        protected global::System.Web.UI.WebControls.Label lblBalancesEmpty;

        protected global::System.Web.UI.WebControls.DropDownList ddlLeaveType;

        protected global::System.Web.UI.WebControls.TextBox txtStartDate;

        protected global::System.Web.UI.WebControls.TextBox txtEndDate;

        protected global::System.Web.UI.WebControls.FileUpload fileAttachment;

        protected global::System.Web.UI.WebControls.TextBox txtReason;

        protected global::System.Web.UI.WebControls.Button btnSubmit;
    }
}
