//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineLeaveManagementSystem
{
    public partial class ChangePassword
    {
        protected global::System.Web.UI.WebControls.Label lblIntroMessage;
        protected global::System.Web.UI.WebControls.Label lblPasswordMessage;
        protected global::System.Web.UI.WebControls.Label lblPasswordSuccess;
        protected global::System.Web.UI.WebControls.TextBox txtCurrentPassword;
        protected global::System.Web.UI.WebControls.TextBox txtNewPassword;
        protected global::System.Web.UI.WebControls.TextBox txtConfirmPassword;
        protected global::System.Web.UI.WebControls.Button btnUpdatePassword;
        protected global::System.Web.UI.WebControls.HyperLink lnkCancelPasswordChange;
    }
}
