//------------------------------------------------------------------------------
// <auto-generated>
//------------------------------------------------------------------------------
namespace OnlineLeaveManagementSystem
{
    public partial class CompanySettings
    {
        protected global::System.Web.UI.WebControls.Label lblSettingsMessage;
        protected global::System.Web.UI.WebControls.TextBox txtPolicyTitle;
        protected global::System.Web.UI.WebControls.DropDownList ddlHolidayRegion;
        protected global::System.Web.UI.WebControls.TextBox txtPolicyText;
        protected global::System.Web.UI.WebControls.CheckBox chkSaturdayOff;
        protected global::System.Web.UI.WebControls.CheckBox chkSundayOff;
        protected global::System.Web.UI.WebControls.Button btnSaveSettings;
        protected global::System.Web.UI.WebControls.Label lblHolidayCardTitle;
        protected global::System.Web.UI.WebControls.TextBox txtHolidayDate;
        protected global::System.Web.UI.WebControls.TextBox txtHolidayName;
        protected global::System.Web.UI.WebControls.CheckBox chkHolidayActive;
        protected global::System.Web.UI.WebControls.Button btnSaveHoliday;
        protected global::System.Web.UI.WebControls.Repeater rptHolidays;
    }
}
