//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineLeaveManagementSystem
{
    public partial class Dashboard
    {
        protected global::System.Web.UI.WebControls.Label lblDashboardMessage;
        protected global::System.Web.UI.WebControls.Label lblTotalRequests;
        protected global::System.Web.UI.WebControls.Label lblPendingRequests;
        protected global::System.Web.UI.WebControls.Label lblApprovedRequests;
        protected global::System.Web.UI.WebControls.Label lblActiveUsers;
        protected global::System.Web.UI.WebControls.Repeater rptRecentRequests;
        protected global::System.Web.UI.WebControls.Label lblRecentRequestsEmpty;
    }
}
