//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineLeaveManagementSystem
{
    public partial class LeaveReports
    {
        protected global::System.Web.UI.WebControls.Label lblResultCount;

        protected global::System.Web.UI.WebControls.Label lblReportMessage;

        protected global::System.Web.UI.WebControls.TextBox txtSearch;

        protected global::System.Web.UI.WebControls.DropDownList ddlStatusFilter;

        protected global::System.Web.UI.WebControls.DropDownList ddlDepartmentFilter;

        protected global::System.Web.UI.WebControls.DropDownList ddlLeaveTypeFilter;

        protected global::System.Web.UI.WebControls.TextBox txtStartDate;

        protected global::System.Web.UI.WebControls.TextBox txtEndDate;

        protected global::System.Web.UI.WebControls.Button btnApplyFilters;

        protected global::System.Web.UI.WebControls.Button btnExportCsv;

        protected global::System.Web.UI.WebControls.Button btnExportPdf;

        protected global::System.Web.UI.WebControls.Button btnExportDocx;

        protected global::System.Web.UI.WebControls.Label lblTotalRecords;

        protected global::System.Web.UI.WebControls.Label lblRequestedDays;

        protected global::System.Web.UI.WebControls.Label lblPendingCount;

        protected global::System.Web.UI.WebControls.Label lblApprovedCount;

        protected global::System.Web.UI.WebControls.Repeater rptReportRows;

        protected global::System.Web.UI.WebControls.Label lblEmptyReport;

        protected global::System.Web.UI.WebControls.Panel pnlPager;

        protected global::System.Web.UI.WebControls.Button btnPreviousPage;

        protected global::System.Web.UI.WebControls.Label lblPageSummary;

        protected global::System.Web.UI.WebControls.Button btnNextPage;
    }
}
