//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineLeaveManagementSystem
{
    public partial class ManageUsers
    {
        protected global::System.Web.UI.WebControls.Label lblUsersMessage;
        protected global::System.Web.UI.WebControls.Label lblUsersSuccess;
        protected global::System.Web.UI.WebControls.Label lblAdminCoverageWarning;
        protected global::System.Web.UI.WebControls.Label lblTotalUsers;
        protected global::System.Web.UI.WebControls.Label lblActiveUsers;
        protected global::System.Web.UI.WebControls.Label lblActiveAdmins;
        protected global::System.Web.UI.WebControls.Label lblPasswordResetsPending;
        protected global::System.Web.UI.WebControls.TextBox txtNewUsername;
        protected global::System.Web.UI.WebControls.TextBox txtNewFullName;
        protected global::System.Web.UI.WebControls.DropDownList ddlNewDepartment;
        protected global::System.Web.UI.WebControls.DropDownList ddlNewRole;
        protected global::System.Web.UI.WebControls.CheckBox chkNewIsActive;
        protected global::System.Web.UI.WebControls.Button btnCreateUser;
        protected global::System.Web.UI.WebControls.Label lblLockedUsers;
        protected global::System.Web.UI.WebControls.TextBox txtUserSearch;
        protected global::System.Web.UI.WebControls.DropDownList ddlDepartmentFilter;
        protected global::System.Web.UI.WebControls.Button btnApplyFilters;
        protected global::System.Web.UI.WebControls.Button btnResetFilters;
        protected global::System.Web.UI.WebControls.Repeater rptUsers;
        protected global::System.Web.UI.WebControls.Label lblUsersEmpty;
    }
}
