//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineLeaveManagementSystem
{
    public partial class ManageRequests
    {
        protected global::System.Web.UI.WebControls.Label lblRequestCount;

        protected global::System.Web.UI.WebControls.Label lblRequestsMessage;

        protected global::System.Web.UI.WebControls.TextBox txtSearch;

        protected global::System.Web.UI.WebControls.DropDownList ddlStatusFilter;

        protected global::System.Web.UI.WebControls.DropDownList ddlDepartmentFilter;

        protected global::System.Web.UI.WebControls.Button btnApplyFilters;

        protected global::System.Web.UI.WebControls.Button btnResetFilters;

        protected global::System.Web.UI.WebControls.Repeater rptRequests;

        protected global::System.Web.UI.WebControls.Panel pnlPager;

        protected global::System.Web.UI.WebControls.Button btnPreviousPage;

        protected global::System.Web.UI.WebControls.Label lblPageSummary;

        protected global::System.Web.UI.WebControls.Button btnNextPage;
    }
}
