//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineLeaveManagementSystem
{
    public partial class MyLeaves
    {
        protected global::System.Web.UI.WebControls.Repeater rptBalances;

        protected global::System.Web.UI.WebControls.Label lblBalancesEmpty;

        protected global::System.Web.UI.WebControls.DropDownList ddlStatusFilter;

        protected global::System.Web.UI.WebControls.Label lblLeavesMessage;

        protected global::System.Web.UI.WebControls.Repeater rptLeaves;
    }
}
