//------------------------------------------------------------------------------
// <auto-generated>
//------------------------------------------------------------------------------
namespace OnlineLeaveManagementSystem
{
    public partial class Notifications
    {
        protected global::System.Web.UI.WebControls.Button btnMarkAllRead;
        protected global::System.Web.UI.WebControls.Label lblNotificationMessage;
        protected global::System.Web.UI.WebControls.Repeater rptNotifications;
        protected global::System.Web.UI.WebControls.Label lblNotificationsEmpty;
    }
}
