//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineLeaveManagementSystem
{
    public partial class PolicyCatalog
    {
        protected global::System.Web.UI.WebControls.Label lblCatalogMessage;
        protected global::System.Web.UI.WebControls.Label lblCatalogSuccess;
        protected global::System.Web.UI.WebControls.TextBox txtDepartmentName;
        protected global::System.Web.UI.WebControls.Button btnCreateDepartment;
        protected global::System.Web.UI.WebControls.Repeater rptDepartments;
        protected global::System.Web.UI.WebControls.TextBox txtLeaveTypeName;
        protected global::System.Web.UI.WebControls.TextBox txtLeaveTypeDefaultDays;
        protected global::System.Web.UI.WebControls.CheckBox chkLeaveTypeRequiresAttachment;
        protected global::System.Web.UI.WebControls.Button btnCreateLeaveType;
        protected global::System.Web.UI.WebControls.Repeater rptLeaveTypes;
    }
}
