//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineLeaveManagementSystem
{
    public partial class SiteMaster
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.ContentPlaceHolder HeadContent;

        protected global::System.Web.UI.WebControls.HyperLink lnkApplyLeave;

        protected global::System.Web.UI.WebControls.HyperLink lnkManageRequests;

        protected global::System.Web.UI.WebControls.HyperLink lnkLeaveReports;

        protected global::System.Web.UI.WebControls.HyperLink lnkNotifications;

        protected global::System.Web.UI.WebControls.Label lblNotificationCount;

        protected global::System.Web.UI.WebControls.HyperLink lnkManageUsers;

        protected global::System.Web.UI.WebControls.HyperLink lnkPolicyCatalog;

        protected global::System.Web.UI.WebControls.HyperLink lnkCompanySettings;

        protected global::System.Web.UI.WebControls.Label lblAvatarInitial;

        protected global::System.Web.UI.WebControls.Label lblCurrentUser;

        protected global::System.Web.UI.WebControls.Label lblCurrentRole;

        protected global::System.Web.UI.WebControls.Label lblPageSubtitle;

        protected global::System.Web.UI.WebControls.HyperLink lnkChangePassword;

        protected global::System.Web.UI.WebControls.LinkButton btnLogout;

        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;

        protected global::System.Web.UI.WebControls.ContentPlaceHolder ScriptsContent;
    }
}
